### ISSUE TITLE
Trying to read JSON from wrong dir

### ISSUE THREAD

**Issue by JackSeaton** [kylekatarnls/update-helper#1]
I'm trying to update composer for a project and it's throwing 
```
RuntimeException - Could not read ... 
file_get_contents(<path>/marketplace-portal/application/composer.json) : failed to open stream: No such file or directory
```

I ran again in verbose mode and it looks like the JSON is being read by the below function in class `UpdateHelper` 

```php
public function __construct(Event $event, IOInterface $io = null, Composer $composer = null)
{
    $this->event = $event;
    $this->io = $io ?: (method_exists($event, 'getIO') ? $event->getIO() : null);
    $this->composer = $composer ?: (method_exists($event, 'getComposer') ? $event->getComposer() : null);

    if ($this->composer) {
        $this->composerFilePath = dirname($this->composer->getConfig()->get('vendor-dir')).'/composer.json';
        $this->file = new JsonFile($this->composerFilePath);
        $this->dependencies = $this->file->read();
    }
}
```

Looks like `$this->composer->getConfig()->get('vendor-dir')` is the issue here. 

This project is setup with a `composer.json` at the root (`marketplace-portal/composer.json`), with `vendor-dir` defined as `"vendor-dir": "application/vendor"` in the `composer.json`.

Because it's trying to read a JSON file that doesn't exist, it's killing the composer process, which is less than ideal.

Any help/suggestions would be greatly appreciated. Thanks

**Comment by tranthienbinh1989** [comment]
i got the same issue when using a custom vendor directory.

**Comment by kylekatarnls** [comment]
Thanks for report, as a first draft I will check if the composer.json is found and else, skip with a non-blocking message.

**Comment by kylekatarnls** [comment]
Hi @JackSeaton and @tranthienbinh1989, could you please retry with the new 1.0.1 if your install pass properly?

Now I will try if Composer Config expose composer.json in its API.

**Comment by kylekatarnls** [comment]
Now it should handle custom vendor-dir. Please let me know if you have any trouble and I would re-open.

**Comment by JackSeaton** [comment]
@kylekatarnls thanks for the speedy fix! Seems to be working on my end!

@tranthienbinh1989 working for you too?
