### ISSUE TITLE
scanning all files with composer >= 2.0.9

### ISSUE THREAD

**Issue by michabbb** [kylekatarnls/update-helper#12]
https://github.com/composer/composer/issues/9760#issuecomment-792356381

https://github.com/Insolita/unused-scanner/issues/36

dear maintainer, there is something strange with that package, since composer version 2.0.9.

please take a look. 

thank you.

**Comment by kylekatarnls** [comment]
Hello,

First move I can advise is upgrading to Carbon ^2 (2.0.0 was out in August 2018). As Carbon end of life is over for more than a year, de advise we won't spend too much effort in making this dead package working with modern composer version.

Then, update-helper on its own does not scan all files, only each `composer.json` which indeed could be slow with a lot of packages and a slow file system. But this would not be impacted by the version of composer in use.

If you would have a stack trace (an identified bottleneck from some profilling dump), it might help to know which composer function/method became slow on 2.0.9. From this point I could eventually propose a fix to composer or try to use something else faster instead.

**Comment by michabbb** [comment]
hi, i have a php7 project and used different composer versions with the same composer.json - and it turned out, that from version 2.0.9 composer was scanning every single file of my project, while 2.0.8 did not. the only composer plugin that exists in my project, is "update-helper" and starting composer with "--disable-plugin" worked fine again. that´s all i can say. but as u mentioned, the version i am talking about - from this package - is old. and i already changed the version of the "unsued-scanner", so in fact, this whole thing is no longer an issue for me. i just wanted to mention it here, in case u are interested in and want to look into it. if you want, you can lose this issue.

**Comment by kylekatarnls** [comment]
Yes without more clue on this, it would be finding a needle in a haystack, and I don't feel it's worth it regarding the low reproduction rate of the issue. Thanks for letting know.
