### ISSUE TITLE
class not found: UpdateHelper\ComposerPlugin

### ISSUE THREAD

**Issue by salvatorelapi** [kylekatarnls/update-helper#2]
Hi, i'm trying to install laravel in vagrant box but i get always this error

composer install

[UnexpectedValueException]
  Plugin kylekatarnls/update-helper could not be initialized, class not found: UpdateHelper\ComposerPlugin

but if i run composer install --prefer-source i haven't error, version of laravel is 5.7

**Comment by kylekatarnls** [comment]
It's very weird because this class (`UpdateHelper\ComposerPlugin`) is present since the first version. Did you try `composer clearcache`?

**Comment by salvatorelapi** [comment]
yes I haven't error just if add --prefer-source my composer version is 1.8.5

Il giorno ven 31 mag 2019 alle ore 10:49 Kyle <notifications@github.com> ha
scritto:

**Comment by kylekatarnls** [comment]
I use composer 1.8.5 too and never use `--prefer-source`, ComposerPlugin is required by composer.json extra.class only and the same composer.json provides it with the PSR-0 autoload.

So we will need more context and infos. First use `composer install -vvv` to get a more verbose output. Then please give me your composer.json (or a minimum one that gives you the error) so I can try to reproduce the bug.

Then please give me your vagrant box settings.

**Comment by salvatorelapi** [comment]
ok now i remove again vendor folder and i try to run compose install -vvv
about vagrant whant you want just vagrant file or also provision ?

Il giorno ven 31 mag 2019 alle ore 11:04 Kyle <notifications@github.com> ha
scritto:

**Comment by salvatorelapi** [comment]
wait. now after that i run composer install -- prefer-source and it update
composer.json now work also composer install. Then probably there was
somethink to broken in my first composer.json

i cleared cache and remove vendor folder before try

Il giorno ven 31 mag 2019 alle ore 11:23 salvatore lapi <
salvatore.lapi@gmail.com> ha scritto:

**Comment by kylekatarnls** [comment]
Glad to here. Please let me know if you find what was wrong for next people who could get the same problem.

**Comment by sgtaziz** [comment]
I am also having this issue, trying to upgrade from Laravel 5.6 - 5.7 in a Vagrant machine. --prefer-source does seem to help, but it seems to also breaks other packages. I've tried clearing composer's cache as well. Running `composer i` or `composer u` still results in the same error. I noticed a commit to change the NameSpace recently (97a54723b1dae845c7b3df87006eb58556788f3d), perhaps its related?

**Comment by sgtaziz** [comment]
Also, attached is a screenshot that shows more errors. This might help
![Screen Shot 2019-05-31 at 5 37 25 PM](https://user-images.githubusercontent.com/5303104/58736158-d4e63580-83ca-11e9-9448-18e660656c4c.png)

**Comment by kylekatarnls** [comment]
The namespace was fixed before the release 1.0.0. And the --prefer-source should give you the exact same package. The commit hash fbfa94c0f1 you downloaded is the right commit and is available in the GitHub repository, so I don't know why it failed to clone it.

My 2 cents: Laravel 5.7 is also deprecated, you should upgrade to 5.8.

**Comment by sgtaziz** [comment]
I just tried it with 5.8 with the same error unfortunately. I’ll do some more testing and see if I can figure it out, I will post a solution for everyone here if I end up finding the issue

**Comment by sgtaziz** [comment]
Fixed it! Issue for me was caused by having atom open through my host machine (mac OS) while trying to run composer. I guess for some reason atom locks some of those git files? Either way it works now, hope it helps someone :)

**Comment by kylekatarnls** [comment]
Thanks for the feedback @sgtaziz. I'm a bit surprised about you have the issue with Laravel 5.8, as with Laravel 5.8, kylekatarnls/update-helper should not even be installed unless you have a PHP version < 7.1.

**Comment by mint-ws** [comment]
Hi Kyle, I'm still getting the same error output as the screenshot provided by @sgtaziz (https://github.com/kylekatarnls/update-helper/issues/2#issuecomment-497868252) and have tried all the suggestions here including clear cache/prefer-source and closing Sublime Text. Recently upgraded to Homestead 8 (Ubuntu 18.04.2).  Vagrant 2.2.4.  Tried with Laravel 5.6 and 5.7 with same result.
Thanks for your help.

**Comment by kylekatarnls** [comment]
When googling `composer plugin could not be initialized, class not found` it seems to be a very common problem happening to many composer plugins. Unless stop using the `composer-plugin-api` it would be hard to fix it from our side.

Most of users having this on other repositories solve it by removing the `vendor` folder.

**Comment by mint-ws** [comment]
In my case, removing the vendor folder does not make any difference. How would I go about skipping/disabling this plugin so I can carry on installing my vendor files?

**Comment by kylekatarnls** [comment]
For now, you can lock carbon dependency adding `"nesbot/carbon": "~1.37.0"`, that's the quick fix. But I highly recommend to rather upgrade to Laravel 5.8.

**Comment by kylekatarnls** [comment]
Maybe you can try a first install `composer install --no-scripts` then re-run `composer install` before doing that.

**Comment by kylekatarnls** [comment]
I will try running a default Laravel 5.7 app with different combinaisons (with vendor, without composer.lock, with composer.lock, without vendors, etc.) and see if I can reproduce.

**Comment by mint-ws** [comment]
Same issue using `composer install --no-scripts`

**Comment by kylekatarnls** [comment]
@mint-ws I tried a lot of combinaison multiple times and no errors:
- without composer.lock, without vendor / composer update
- without composer.lock, without vendor / composer install
- with composer.lock, without vendor / composer update
- with composer.lock, without vendor / composer install
- without composer.lock, with vendor / composer update
- without composer.lock, with vendor / composer install

Do you get the same error when running `composer install` on an other machine (for example a non Vagrant localhost environment)?

**Comment by mint-ws** [comment]
Thanks, I tried on another vagrant machine and same error. Note this is with Laravel 5.6.* so I will try to update to 5.8 and see what happens.

**Comment by kylekatarnls** [comment]
An other possibility is a broken state of composer.lock (if you commit it in your project). That would imply to run `composer update` (can be with the original composer.json without updating Laravel) to generate a "fresh" composer.lock then retry to install using this composer.lock.

But upgrading to Laravel 5.8 is the best move since Laravel no longer release updates for Laravel <= 5.7.

**Comment by kylekatarnls** [comment]
It seems Vagrant may have an incompatibility as per https://github.com/kylekatarnls/update-helper/issues/3#issuecomment-499593996

You can try:
```shell
curl -sS https://getcomposer.org/installer | php
php composer.phar install
```

To use a freshly downloaded composer install instead of the Vagrant one.

**Comment by seanmoghadam** [comment]
`sudo composer install --prefer-source` 
solved the issue for me
Laravel Version 5.6.x

EDIT: This lead to other errors

First answer solved my  issue:
https://stackoverflow.com/questions/56757578/composer-fails-with-kylekatarnls-update-helper-on-new-homestead?newreg=b488692d6b52468aa7370b036a71d255

with this approach a reinstallation of Homestead vagrant box is required

**Comment by Britic** [comment]
I had this problem and using prefer-dist didn't give me all the classes I needed.

I ran `composer global require kylekatarnls/update-helper
`

which did the global install and solved he problem.

**Comment by zichril** [comment]
sudo rm -rf vendor/
composer install

solved my problem
