### ISSUE TITLE
Error in composer update

### ISSUE THREAD

**Issue by eliasjtg** [kylekatarnls/update-helper#3]
Dependency resolution completed in 0.001 seconds
Package operations: 7 installs, 28 updates, 0 removals
Installs: kylekatarnls/update-helper:1.1.1, psr/http-factory:1.0.1, symfony/mime:v4.3.0, symfony/event-dispatcher-contracts:v1.1.1, symfony/polyfill-php73:v1.11.0, symfony/service-contracts:v1.1.2, symfony/translation-contracts:v1.1.2
Updates: zendframework/zend-diactoros:2.1.2, symfony/http-foundation:v4.3.0, phpseclib/phpseclib:2.0.17, lcobucci/jwt:3.3.1, league/oauth2-server:7.4.0, symfony/css-selector:v4.3.0, symfony/var-dumper:v4.3.0, symfony/routing:v4.3.0, symfony/process:v4.3.0, symfony/event-dispatcher:v4.3.0, symfony/debug:v4.3.0, symfony/http-kernel:v4.3.0, symfony/finder:v4.3.0, symfony/console:v4.3.0, egulias/email-validator:2.1.8, opis/closure:3.3.0, symfony/translation:v4.3.0, nesbot/carbon:1.38.4, league/flysystem:1.0.52, nikic/php-parser:v4.2.2, nexmo/client:1.8.1, laravel/passport:v7.3.0, nob/database:v5.7.3, nco/files:v5.7.6, nob/support:v5.7.2, sebastian/environment:4.2.2, phpdocumentor/reflection-docblock:4.3.1, phpunit/phpunit:7.5.12
  - Installing kylekatarnls/update-helper (1.1.1): Reading /home/vagrant/.composer/cache/files/kylekatarnls/update-helper/b43c77a2aeb46815c21e75203bfa7b68c3c25b08.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/home/vagrant/code/dgatech-backend/vendor/kylekatarnls/update-helper/da3b7597c7d9f2d3ee52d3f7ad659ba4' -d '/home/vagrant/code/dgatech-backend/vendor/composer/c9d19c0d'
Plugin installation failed, rolling back
  - Removing kylekatarnls/update-helper (1.1.1)

                                                                               
  [RuntimeException]                                                           
  Could not delete /home/vagrant/code/dgatech-backend/vendor/kylekatarnls/upd  
  ate-helper/src/UpdateHelper:                                                 
                                                                               

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:217
 Composer\Util\Filesystem->unlink() at phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:170
 Composer\Util\Filesystem->removeDirectoryPhp() at phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:137
 Composer\Util\Filesystem->removeDirectory() at phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownloader.php:238
 Composer\Downloader\FileDownloader->remove() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:299
 Composer\Downloader\DownloadManager->remove() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:224
 Composer\Installer\LibraryInstaller->removeCode() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:137
 Composer\Installer\LibraryInstaller->uninstall() at phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php:66
 Composer\Installer\PluginInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:595
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:229
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:163
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by eliasjtg** [comment]
Composer version 1.8.5 2019-04-09 17:46:47

**Comment by eliasjtg** [comment]
composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.5
PHP version: 7.3.6
PHP binary path: /usr/bin/php7.3

**Comment by kylekatarnls** [comment]
Hello,

"Could not delete" sounds like a permission denied and the update-helper does not appear in the error stack trace, so possibly not an issue directly related to the package.

Can you activate the verbose mode, option `-vvv` of composer and see if more errors appears before "Plugin installation failed, rolling back"?

Did you try `composer clearcache` and removing the vendor directory?

**Comment by eliasjtg** [comment]
Hi,

The trace is with -vvv, and i try `composer clearcache` and nothing.

This seems like an error of homestead or vagrant.

I finish by executing the composer commands like this:

curl -sS https://getcomposer.org/installer | php and php composer.phar [composer command] in my local machine and work fine.

At first I thought it should be the update of your plugin because only a few hours ago that with composer install I had installed everything correctly.

Thank you for your time

**Comment by kylekatarnls** [comment]
Thanks for you feedback. It may be related, as this package requires `composer-plugin-api` which is a special internal dependency of composer, it may "reveal" problems you wouldn't have without it.
