### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by saraklor** [kylekatarnls/update-helper#6]
Hi, 
I am trying to run composer install anf get the following error:
 ```
 Problem 1
    - Installation request for kylekatarnls/update-helper 1.1.1 -> satisfiable by kylekatarnls/update-helper[1.1.1].
    - kylekatarnls/update-helper 1.1.1 requires composer-plugin-api ^1.1.0 -> no matching package found.
  Problem 2
    - kylekatarnls/update-helper 1.1.1 requires composer-plugin-api ^1.1.0 -> no matching package found.
    - nesbot/carbon 1.25.3 requires kylekatarnls/update-helper ^1.1 -> satisfiable by kylekatarnls/update-helper[1.1.1].
    - Installation request for nesbot/carbon 1.25.3 -> satisfiable by nesbot/carbon[1.25.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

```

could you please assist?

**Comment by kylekatarnls** [comment]
`composer-plugin-api` is an internal API of composer. You should have a very old version of composer.

Please run:
```
composer self-update
```

Then check your version if it does not solves your error.

**Comment by kylekatarnls** [comment]
Or maybe you run the dev version of 2.0?

**Comment by dmitriy-dev** [comment]
- Installing kylekatarnls/update-helper (1.2.0): Cloning 5786fa188e
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+6fc5ed78768c+2020-01-22+0451
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.

**Comment by kylekatarnls** [comment]
Sounds like you have a proxy or invalid ssh settings. Regarding the output, you're also using `--prefer-source` which is slower and only useful in very rare cases. Use `--prefer-dist` (should be the default settings if you remove prefer-source settings from composer.json and CLI arguments) unless you actually need it. In this case, please detail you setup: the composer.json content, proxy if you have and the command you run.

**Comment by kylekatarnls** [comment]
The issue here seems not related to the package itself and I have not enough details to reproduce the issue. Feel free to provide more infos so I can re-open and dig into it.
