### ISSUE TITLE
Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by bitw** [kylekatarnls/update-helper#7]
Fatal error: Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /home/teamcity/2017.2.3/buildAgent/work/942ad3a15f527ecb/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11

**Comment by kylekatarnls** [comment]
Please provide:
- [x] The code/command you run
- [x] The result you expected from this code/command
- [x] Your composer.json
- [x] The PHP version you run

**Comment by bitw** [comment]
- composer install -vvv
- install packages

https://pastebin.com/vTP4HWyC

$php -v
PHP 7.1.33 (cli) (built: Mar 17 2020 09:14:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by kylekatarnls** [comment]
Hi, may also know your version of composer?

I will dig deeper, but for now I can yet see a blocking point: you use laravelrus/localized-carbon

This package actually breaks Carbon as Carbon yet support localization for a long time (since 1.18) and has way more feature and languages available than localized-carbon including of course `diffForHumans()`, and this package also prevent you from upgrading to Carbon 2 and so to modern Laravel versions.

I will try to make this package compatible with. But even if I do, you may be warned you have many no-longer-supproted or obsolete packages.

I would highly recommend to remove the package laravelrus/localized-carbon (which makes no point), then a good next step would be to upgrade Laravel to at least 5.8.

**Comment by bitw** [comment]
$ composer --version
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.4.1 2017-03-10 09:29:45

Disabling the carbon localization package did not help.

Unfortunately, there is no way to upgrade the project to version 5.8 or higher.

**Comment by bitw** [comment]
Updated composer.
$ composer --version
Do not run Composer as root / super user! See https://getcomposer.org/root for details
Composer version 1.10.1 2020-03-13 20:34:27

The result is the same.

**Comment by kylekatarnls** [comment]
I did not say removing laravelrus/localized-carbon would fix this error, I said it's useless as Carbon already has localization, so it's blocking features provided by default and it prevents to update Laravel.

And Composer 1.4.1 or 1.10.1 does not contain deactivate and uninstall methods in PackageInterface as you can see:

https://github.com/composer/composer/blob/1.4.1/src/Composer/Package/PackageInterface.php

So I don't know where those `Composer\Plugin\PluginInterface` methods come from. Note than this package has been installed properly thousand times so it looks like a package is overriding Composer stuff and this sounds bad.

**Comment by bitw** [comment]
There is a suspicion that the problem is in the TeamCity service.

**Comment by jonnybarnes** [comment]
To add to this conversation, the company I work for have started seeing this same error in our GitHub Actions this week.

**Comment by kylekatarnls** [comment]
Clearly not due to a change in the update-helper package as we did not release any version of this package since July.

**Comment by bitw** [comment]
Suspicions came true. ТeamСity by default started using composer 2.0-dev. For this reason, the assembly of the project broke down.

**Comment by jonnybarnes** [comment]
Same, one of our phpunit setup scripts downloads `https://getcomposer.org/composer.phar` which has started returning `2.0-dev`.

**Comment by kylekatarnls** [comment]
Indeed, Composer added this methods in its development branch last week:
https://github.com/composer/composer/commit/3fc9ede24b85cbca0914060e6043abdc2cb1e406#diff-9761e5e6cef580d24c5a05d870dcc479

It's not yet released.

I will add these methods to be ready. But we clearly can't take the responsibility to be compatible with unreleased changes as soon as they are commited ;)

**Comment by zeshan77** [comment]
I was facing the same issue and the reason was using `composer 2`, downgrading it to `version 1` worked fine for me.

**Comment by kylekatarnls** [comment]
Once you will update your other dependencies you will be able to safely upgrade again to composer 2 (and you should). The whole point of this library is to help you to stay up to date and safe.

Taking upgrade paths will save your time on the long run while taking downgrade paths will bring you more troubles soon again.

**Comment by tpaksu** [comment]
I had nothing modified in my vendor folder, and reinstalling packages wouldn't be a problem for me, so my solution was this:

```bash
rm -rf vendor
rm -f composer.lock
composer install
```

worked for me. 

**Use at your own risk. I'm not responsible  for anything :) Just showing you another way to overcome this.**

**Comment by Playbits** [comment]
```
rm composer.lock
composer install
```
# Worked for me Like charm

**Comment by garhbod** [comment]
```
rm -rf vendor
composer require kylekatarnls/update-helper:"^1.2.1"
```
That way you don't loose all your current versions in the lock file

**Comment by Nghiait123456** [comment]
i use Composer version 2.0.8 2020-12-03 17:20:38 is error
i back composer version 1.8.6 pass

**Comment by kylekatarnls** [comment]
This has been [mentioned before](https://github.com/kylekatarnls/update-helper/issues/7#issuecomment-732057614)
Please also [read this note](https://github.com/kylekatarnls/update-helper/issues/7#issuecomment-732160204)

**Comment by qq274805539** [comment]
composer self-update -r

**Comment by kobusbeets** [comment]
> Fatal error: Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /home/teamcity/2017.2.3/buildAgent/work/942ad3a15f527ecb/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11

1. Make sure you have composer 2+ installed. You can run `composer self-update` to upgrade it to composer 2+.
2. Remove the composer.lock file.
3. Remove the vendor directory.
4. Run `composer update`

If your project dependencies were installed with composer < 2, then it is likely that you will encounter this error when trying to install new or update existing project dependencies using composer 2+.

**Comment by ankurk91** [comment]
```bash
rm -rf vendor/kylekatarnls/update-helper
composer update kylekatarnls/update-helper
```

this worked for me with composer v2

**Comment by Oyelamin** [comment]
@ankurk91 You did well man!

**Comment by moamahfouz** [comment]
> I had nothing modified in my vendor folder, and reinstalling packages wouldn't be a problem for me, so my solution was this:
> 
> ```shell
> rm -rf vendor
> rm -f composer.lock
> composer install
> ```
> 
> worked for me.
> 
> **Use at your own risk. I'm not responsible for anything :) Just showing you another way to overcome this.**

thanks. It works very fine.

**Comment by qazihamayun** [comment]
> ```
> rm -rf vendor
> composer require kylekatarnls/update-helper:"^1.2.1"
> ```
> 
> That way you don't loose all your current versions in the lock file

This helped me... Thanks

**Comment by moxerox** [comment]
Just came by this problem while working on an old project. 

`composer update` 

and everything is looking great
